### ISSUE TITLE
Assertion error with duration=True for SRTparser object (Python 3)

### ISSUE THREAD

**Issue by rbawden** [pyannote/pyannote-parser#1]
parser = SRTParser(split=True, duration=True)
pathtosrt = series.path_to_subtitles(episode, language=lang)
subs_obj = parser.read(pathtosrt)()

produces the following error:

    subs_obj = parser.read(pathtosrt)()
  File "/people/bawden/workspace/tvd/venv/lib/python3.4/site-packages/pyannote/parser/transcription/srt.py", line 153, in read
    transcription.add_edge(start_t, end_t, subtitle=line)
  File "/people/bawden/workspace/tvd/venv/lib/python3.4/site-packages/pyannote/core/transcription.py", line 76, in add_edge
    assert t1 <= t2
AssertionError

The error is only produced when duration=True (i.e. 'split=True, duration=False' works fine)

**Comment by hbredin** [comment]
It would be great if you could provide an example of the SRT file causing the problem.
Even better -- if you could add a "unit test" with a very simple failing example, that would be great.
See https://github.com/pyannote/pyannote-parser/blob/develop/tests/test_srt.py

**Comment by rbawden** [comment]
The problem appears to be with blank subtitles such as:
287
00:29:52,200 --> 00:29:53,599

(i.e. no text under time codes).
If I delete this example from the srt file (here it's GoT season 01 episode 01), everything works ok.

**Comment by hbredin** [comment]
Fixed in pyannote.parser 0.4.2
